# Generated by Django 5.1.3 on 2024-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
