# Generated by Django 5.1.3 on 2024-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_categories_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('', 'Select category'), ('G', 'Games'), ('O', 'Other')], default='\x00', max_length=3),
        ),
    ]
