# Generated by Django 5.1.3 on 2024-12-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_categories_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('', 'Select category'), ('G', 'Games'), ('O', 'Other')], default='nul', max_length=3),
        ),
    ]
