# Generated by Django 5.1.3 on 2024-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('G', 'Games'), ('O', 'Other')], default='z', max_length=3),
        ),
    ]
