# Generated by Django 5.1.3 on 2024-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_delete_bids_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('G', 'Games'), ('O', 'Other')], default='O', max_length=3, null=True),
        ),
    ]
