# Generated by Django 5.1.3 on 2024-12-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
    ]
