# Generated by Django 5.1.3 on 2024-12-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('G', 'Games'), ('O', 'Other')], default='O', max_length=3, null=True),
        ),
    ]
