# Generated by Django 5.1.3 on 2024-12-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='user_id',
            new_name='user',
        ),
    ]
