# Generated by Django 5.1.3 on 2024-12-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_user_id_listings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='end_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='listings',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
        ),
    ]
