# Generated by Django 5.1.3 on 2025-01-01 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listings_end_date_listings_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
