# Generated by Django 5.1.3 on 2025-01-02 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.date(2025, 1, 2)),
        ),
        migrations.AlterField(
            model_name='listings',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 2)),
        ),
    ]
