# Generated by Django 5.1.3 on 2025-01-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_categories_alter_listings_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('G', 'Games'), ('O', 'Other')], default='O', max_length=3, null=True),
        ),
    ]
