# Generated by Django 5.1.3 on 2025-01-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_rename_name_categories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
    ]
